### ISSUE TITLE
Community definition

### ISSUE THREAD

**Issue by JherezTaylor** [JherezTaylor/Datamining-Reddit#5]
It's not enough to just show of graph of the communities, we must be able to prove that they are related. Explore the attributes and see if it is possible to use them to label the communities. 

Preliminary thoughts are to use the author_flair and the timestamp. For example, the baseball subreddit has the different team names as the author_flair.

Time to reply to a comment. Is the delay in how long it took to reply to a comment a useful indicator of engagement? Example, is a person more likely to respond to their friends faster. 

Think about interest in the same topic vs community. IE, commenting under a subreddit topic vs replying to a comment in a subreddit topic. Consider the depth of replies. 

Validate, the result should show that the graph is a result of the community and not the subreddit.
![702936_10206195391376409_271081676_n](https://cloud.githubusercontent.com/assets/8041270/12015213/1dbbd6e2-ad74-11e5-9b58-0f94a2077ad6.jpg)
![12431293_10206199924369731_1547279953_n](https://cloud.githubusercontent.com/assets/8041270/12015214/1dc6cde0-ad74-11e5-8ba6-150e9193ea78.jpg)
![12435664_10206191157710570_1347490497_n](https://cloud.githubusercontent.com/assets/8041270/12015215/1dce1424-ad74-11e5-86a5-e9dce9350aee.jpg)

**Comment by jeydlex** [comment]
![second community with teams](https://cloud.githubusercontent.com/assets/9431145/12022618/170554da-ad57-11e5-8d6e-7cb1d185fb8c.png)

**Comment by jeydlex** [comment]
![sample plot teams biggest community](https://cloud.githubusercontent.com/assets/9431145/12035577/b97bf028-ae03-11e5-8bfb-f5d0d26ccc7e.png)
For the community with more members in this graph, these are the teams... the one with no legend is NA... users who have not chosen a team

**Comment by JherezTaylor** [comment]
Need to find away to identify which team a user with NA is most likely to belong as it is a significant proportion of the data.

**Comment by jeydlex** [comment]
Sure, for that we must evaluate the number of NA authors in each community... this feels like some sort of classification

**Comment by jeydlex** [comment]
![teams distribution baseball subreddit](https://cloud.githubusercontent.com/assets/9431145/12037194/357004ea-ae12-11e5-9135-b24407fbc34b.png)
Total number of teams in the baseball subreddit

**Comment by jeydlex** [comment]
![communities in baseball](https://cloud.githubusercontent.com/assets/9431145/12055231/ef68c934-aef0-11e5-9323-6ae41c5db0b4.png)

**Comment by jeydlex** [comment]
![communities in baseball 2](https://cloud.githubusercontent.com/assets/9431145/12060746/e38e3176-af3b-11e5-81b9-337ee5322b3c.png)

**Comment by jeydlex** [comment]
![fast greedy top community data](https://cloud.githubusercontent.com/assets/9431145/12073721/4969a4a4-b0f3-11e5-8bc1-7aa282bf7ff4.png)

**Comment by jeydlex** [comment]
![community with spinglass algorithm](https://cloud.githubusercontent.com/assets/9431145/12073725/67698366-b0f3-11e5-8655-0e3348ec457a.png)
